### ISSUE TITLE
Call to FlashMessage->getClass breaks Extension Configuration view in BE

### ISSUE THREAD

**Issue by hirnschmalz** [xperseguers/t3ext-extractor#15]
If using the master branch with TYPO3 9 LTS the usage of `$flashMessage->getClass()` in `Classes/Em/ConfigurationHelper.php` breaks the **Settings** > **Extension Configuration** in the backend.

**Comment by mediaessenz** [comment]
There are much bigger problems:
The master version still uses old api calls inside the MappingController.
Even replacing e.g. `BackendUtility::getAjaxUrl('extractor_analyze')` with `$uriBuilder->buildUriFromRoute('ajax_extractor_analyze')` doesn't work, because there are no routes available.
I think it's because TYPO3 9's Extension Settings Controller is now part of the Install Module, which doesn't always has a backend.

**Comment by hirnschmalz** [comment]
@xperseguers any plans to make this extension TYPO3 v9 compatible?

**Comment by xperseguers** [comment]
@hirnschmalz Jigal van Hemert started to work on some compatibility, you may contact him on Slack if you want to help. I will naturally integrate the changes when they get available.

**Comment by kaystrobach** [comment]
@hirnschmalz maybe you checkout the pr #17 - feedback would be awesome!

**Comment by hirnschmalz** [comment]
Hi @kaystrobach ,

I'm using your PR in two installations. No problems so far. 👍
