### ISSUE TITLE
Native Typo3 9 or 10 Support

### ISSUE THREAD

**Issue by MediKathi** [xperseguers/t3ext-extractor#21]
Hello,

will this extension get typo3 v9 or v10 support?

**Comment by xperseguers** [comment]
yes

**Comment by xperseguers** [comment]
Compatibility with v9 should be fine since it contains basically all what's needed and said to work from

https://github.com/xperseguers/t3ext-extractor/pull/17

Anyway, further work is currently done on https://github.com/xperseguers/t3ext-extractor/tree/feature/typo3-v10 for official compatibility with v8, v9 and v10. Please stay tuned and/or report problems as dedicated tickets.
