### ISSUE TITLE
Extraction of PDF-metadata since version 1.7.1

### ISSUE THREAD

**Issue by responseinformationsdesign** [xperseguers/t3ext-extractor#26]
Since version 1.7.1 extraction of metadata does not work anymore (Windows IIS/TYPO3 8.7.32/PHP 7.2.30). Version 1.7.0 works flawlessly.

**Comment by seirerman** [comment]
Same problem here on TYPO3 8.7.34. Sticking with 1.7.0 works for us for now.

We don't use Tika, but exiftool, pdfinfo and native PHP.

I haven't tested extractor on TYPO3 9 oder 10, though.

**Comment by xperseguers** [comment]
Please better explain what "does not work": nothing at all gets extracted? Gibberish  is extracted?

@seirerman: exiftool is not used for PDF, only pdfinfo and native PHP.

**Comment by seirerman** [comment]
Sorry, I should have been more clear:

I have a prepared pdf and docx file containing metadata. None of those values are inserted in the FAL metadata after importing them when I use version 1.7.2.

However, the FAL metadata is imported correctly when I use version 1.7.0. The extension config is the same.

I could attached those files in case you need them...

**Comment by xperseguers** [comment]
Attaching them could certainly help. What could help as well is you, testing the mapping tool provided in Admin Tools > Settings > Extractor > Mapping. Put your sample files within `fileadmin/user_upload/` and try the various services (pdfinfo, PHP, ...) to see if the problem is specific to a given tool, if the mapping needs to be adapted, ...

**Comment by responseinformationsdesign** [comment]
Preview in the extension settings works for all services. But when uploading new files nothing is  extracted to TYPO3. Tested with different instances, different versions (8.7 and 9.5) and different files.

**Comment by seirerman** [comment]
Tested again with 1.7.2 on TYPO3 9.5. I also added and configured the Tika app (.jar).

The mapping test in the extension settings seems to work, but actually uploading a document results in an empty set of metadata in sys_file_metadata.

I've attached my test files: [metadata.zip](https://github.com/xperseguers/t3ext-extractor/files/4850213/metadata.zip)

1.7.0 still works on TYPO3 9.5, though.

**Comment by xperseguers** [comment]
@seirerman Is it related to Tika or not? Does it work if you do not configure Tika? Please add further information on how to properly reproduce. Possibly explain which file to choose to upload and which field should be checked for which metadata info so that reproducing and testing is easier than figuring everything out.

**Comment by chrissonntag** [comment]
I'm not quite sure but it could be that it's related to the fact that the interface method canProcess() has been removed but instead exchanged with _canProcess() which should be called by parent::canProcess() but only if there aren't any metaData been extracted by core already. So the appropriate method extractMetaData (in our case of service PhpMetadataExtraction) will never be called. Unless there is a way to prevent the core from getting the metaData by itself?!
However, if we change protected method _canProcess() back to public method canProcess() the extraction works as designed.

**Comment by subnoodle** [comment]
Is related with: [(https://github.com/xperseguers/t3ext-extractor/issues/28)]

**Comment by j-schumann** [comment]
I think the change in the interface method usage is intended to prepend the version check in AbstractExtractionService::canProcess, which itself is not a bad thing.

The problem seems to be that Typo3 returns an array of metadata with mostly empty/null values (at least in Typo 8.7.34) and is _not_ related to Tika but also occurs with the PHP extractor:

```
-- debug from AbstractExtractionService.php#L160
Fri, 17 Jul 2020 18:47:52 +0200 [DEBUG] request="889dc3638d2f7" component="Causal.Extractor.Service.Extraction.PhpMetadataExtraction": Causal\Extractor\Service\Extraction\AbstractExtractionService::canProcess - {"meta":{"uid":2086,"pid":0,"tstamp":1595004472,"crdate":1595004472,"cruser_id":163,"sys_language_uid":0,"l10n_parent":0,"l10n_diffsource":"","t3ver_oid":0,"t3ver_id":0,"t3ver_wsid":0,"t3ver_label":"","t3ver_state":0,"t3ver_stage":0,"t3ver_count":0,"t3ver_tstamp":0,"t3ver_move_id":0,"t3_origuid":0,"file":2105,"title":null,"width":1110,"height":452,"description":null,"alternative":null,"categories":0,"l10n_state":null,"visible":1,"status":"","keywords":null,"caption":null,"creator_tool":"","download_name":"","creator":"","publisher":"","source":"","copyright":null,"location_country":"","location_region":"","location_city":"","latitude":"0.00000000000000","longitude":"0.00000000000000","ranking":0,"content_creation_date":0,"content_modification_date":0,"note":null,"unit":"","duration":0,"color_space":"","pages":0,"language":"","fe_groups":null,"camera_make":"","camera_model":"","camera_lens":"","shutter_speed":"","focal_length":0,"exposure_bias":"","white_balance_mode":"","iso_speed":0,"aperture":0}}
```

While the extension expects an empty array in https://github.com/xperseguers/t3ext-extractor/blob/master/Classes/Service/Extraction/AbstractExtractionService.php#L160
I don't know if this construct works in other Typo versions or if there was a bug fix in the Type core that now returns the empty data extracted by the core instead of the empty array.

**Comment by xperseguers** [comment]
The comment you mention on line 160 explains that the block is related to https://forge.typo3.org/issues/91168

**Comment by j-schumann** [comment]
Thanks, I've seen that issue. But the problem is that Typo returns a non-empty array even when a file is uploaded, not only when moved.

**Comment by derhansen** [comment]
Exactly, this [line](https://github.com/xperseguers/t3ext-extractor/blob/master/Classes/Service/Extraction/AbstractExtractionService.php#L160) also prevents meta data extraction on file upload. I fully agree on the design flaw in FAL, but I think this scenario should be handled different.

**Suggestion for workaround:** 
When an image is uploaded and/or metadata has already been automatically extracted, `sys_file_metadata.tstamp` and `sys_file_metadata.crdate` are equal. As soon as the editor modifies file metadata manually, `sys_file_metadata.tstamp` is overwritten with the current timestamp. Respecting this scenario in `AbstractExtractionService` could be used to prevent automatic metadata extraction.

**Comment by xperseguers** [comment]
@derhansen checking with `crdate` and `tstamp` would indeed by fine with me, wanna prepare a PR?
