### ISSUE TITLE
String is a reserved word and may break in newer PHP versions

### ISSUE THREAD

**Issue by kaystrobach** [xperseguers/t3ext-extractor#6]
https://github.com/xperseguers/t3ext-extractor/blob/cd70b82c34728cf8b8178a424d31c641715f36b0/Classes/Utility/String.php#L26

Please rename that class:

```
Parse error: web/typo3conf/ext/extractor/Classes/Utility/String.php:26
    24|  * @deprecated Use \Causal\Extractor\Utility\SimpleString instead since this class name is not supported by PHP 7
    25|  */
  > 26| class String
    27| {
    28|     /**
Cannot use 'String' as class name as it is reserved in web/typo3conf/ext/extractor/Classes/Utility/String.php on line 26
```

**Comment by kaystrobach** [comment]
it was just a warning, that popped up during code review. And as you stated php 7.2 compatibility i thought it's worth to mention it.

Thank you for taking care.

**Comment by xperseguers** [comment]
Sure, as stated this class is absolutely not used if you install extractor nowadays but might have been used if you created your own mapping in an older version (> 1 year or so) and kept using it without migrating it. As such, the extension is fully compatible with PHP 7.2 and since the extension is kept compatible with PHP 5.5, technically speaking, the class is fine if present (although again, not used anymore).

Eventually this class will disappear anyway, it's marked as deprecated for a long time, not used anymore and may be removed anytime now.

**Comment by kaystrobach** [comment]
ok, so i close it for now
